// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MouseSite.Data;

#nullable disable

namespace MouseSite.Migrations
{
    [DbContext(typeof(MouseDbContext))]
    [Migration("20240127094136_SeedTheData")]
    partial class SeedTheData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MouseSite.Models.Categ", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("MyProperty3")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categs");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            MyProperty3 = 0,
                            Name = "SciFi"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            MyProperty3 = 0,
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            MyProperty3 = 0,
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 4,
                            DisplayOrder = 24,
                            MyProperty3 = 0,
                            Name = "Fantasy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
